void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _sqrt_recursion(int n);
int power(int x, int y);
int is_prime_number(int n);
int prime(int x, int y);
int boolean(char *x, int start, int end);
int is_palindrome(char *s);
